### ISSUE TITLE
Can't get example to work. Column with name row, not found in table: 

### ISSUE THREAD

**Issue by eele94** [flow-php/etl-adapter-dbal#108]
Hello I'm looking forward to use this library but I'm running into basic problems..

I tried to load and write the same data from one table to another, but that already seems to fail.

```
        (new Flow())
            ->read(
                DbalQueryExtractor::single($connection, "SELECT * FROM {$sourceTable} limit 200", [], [])
            )
            ->write(
                DbalLoader::fromConnection($connection, $destinationTable, $chunkSize, [], 'insert')
            )
            ->run();
```
Throws error: `Column with name row, not found in table: `

Why the loader doesn't unwrap the 'row' value or how do I make it work?

**Comment by norberttech** [comment]
> Why the loader doesn't unwrap the 'row' 

Because loaders responsibility is to just extract data from the source, not all sources are as straightforward as rdbms db tables, so auto unpacking is not that simple. 

What you are missing after reading from the source is the following: 

```
->rows(Transform::array_unpack('row'))
```

You can find better example here: https://github.com/flow-php/flow/blob/1.x/examples/topics/db/db_to_db_sync.php

**Comment by norberttech** [comment]
I'm closing this issue as I believe you found your answer, if that's not the case feel free to leave some more comments
